// Try catch 
// en caso de que haya un error dime cual es el error
// se utiliza para hacer pruebas y errores 

const num1 = 20;
const num3 = 30;

console.log(num1);

try {
    console.log(num2);
} catch (error) {
    console.log(error);
    
}
console.log(num2);
console.log(num3);